name: Push Actions
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "${{ github.event_name }} event at add-datetime-here for ${{ github.repository }} running on ${{ runner.os }}..."

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Closing
        run: echo "   Job ending with ${{ job.status }}..."
