name: Push Actions
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "${{ github.event_name }} event job starting on ${{ runner.os }} for ${{ github.repository }}..."

      - name: Print PATH, pathnames, and versions
        run: |
          echo $PATH
          which python
          python --version
          which java
          java -version
          which ant
          ant -version

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Python tests
        run: ant -buildfile python/build.xml test

      - name: Closing
        run: echo "${{ github.event_name }} event job ending with ${{ job.status }}..."
