on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event_name }} event at ${{ }} for ${{ github.repository }} running on ${{ runner.os }}..."
      - run: echo "checking out repo..."
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls -F ${{ github.workspace }}
      - name: Run Python Tests
      	run: |
	  ant -buildfile python/build.xml
      - run: echo "   Job ending with ${{ job.status }}..."
