name: Push Actions
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "${{ github.event_name }} event at add-datetime-here for ${{ github.repository }} running on ${{ runner.os }}..."

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Print Path
        run: echo $PATH

      - name: Find Python Pathname
        run: which python

      - name: Print Python Version
        run: python --version

      - name: Find Java Pathname
        run: which java

      - name: Print Java Version
        run: java -version

      - name: Print Pathnames
        run: |
	  which python
	  which java

      - name: Closing
        run: echo "   Job ending with ${{ job.status }}..."
